import {
  hypothesisParamsSchema,
  inspectFileParamsSchema,
  listWorkspaceParamsSchema,
  readFileParamsSchema,
  readToolOutputChunkParamsSchema,
  reportProgressParamsSchema,
  requestHandoffParamsSchema,
  requestReflectionParamsSchema,
  runPythonParamsSchema,
  searchToolOutputParamsSchema,
  submitFlagCandidateParamsSchema,
  writeWorkFileParamsSchema,
} from "@rio/domain";
import type { ToolDescriptor } from "./types.js";
import {
  inspectFileTool,
  listWorkspace,
  readChallengeFile,
  readToolOutputChunk,
  reportProgressTool,
  requestHandoffTool,
  requestReflectionTool,
  runPython,
  searchToolOutput,
  submitFlagCandidateTool,
  writeWorkFile,
} from "../tools.js";
import { recordHypothesisTool as recordHypothesis } from "../semantic-tools.js";

function wrap(
  run: (ctx: Parameters<ToolDescriptor["run"]>[0], params: unknown, meta?: { toolIndex: number; startedAt: number }) => Promise<ToolResultLike> | ToolResultLike,
): ToolDescriptor["run"] {
  return async (ctx, params, meta) => Promise.resolve(run(ctx, params, meta));
}

type ToolResultLike = Awaited<ReturnType<ToolDescriptor["run"]>>;

const PATH = { name: "path", type: "string", required: true, description: "Workspace-relative path (root, not work/).", acceptedFormats: ["challenge.txt", "input/a.bin", "artifacts/x"] };

export function coreToolsWithoutMeta(): ToolDescriptor[] {
  const tools: ToolDescriptor[] = [
    {
      name: "list_workspace",
      group: "WORKSPACE",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "List a workspace directory. Omit path or use '.' for the root (challenge.txt, input/, work/, artifacts/).",
      whenToUse: ["Start of a solve to see attachments", "After extract_archive to see new files"],
      whenNotToUse: ["Do not use run_python os.listdir to find files"],
      prerequisites: [],
      schema: listWorkspaceParamsSchema,
      parameters: [{ name: "path", type: "string", required: false, description: "Directory relative to workspace root.", example: "input" }],
      examples: [{ title: "root", situation: "See attachments", args: { path: "." }, expectedSummary: "listed" }],
      output: { description: "Directory entries plus a peek into input/work/artifacts when listing root.", importantFields: ["entries", "children"], interpretation: ["Empty input/ means attachments are not downloaded yet."] },
      failureModes: [{ code: "NOT_FOUND", meaning: "Path does not exist.", recovery: "List '.' first." }],
      suggestedNextTools: ["inspect_file", "read_challenge_file"],
      cost: "CHEAP",
      tags: ["ls", "files", "inventory"],
      run: wrap(listWorkspace),
    },
    {
      name: "read_challenge_file",
      group: "WORKSPACE",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Read a workspace file as text. Use for challenge.txt and small extracted files.",
      whenToUse: ["Read the problem statement", "Read a small decoded text artifact"],
      whenNotToUse: ["Do not read huge binaries; inspect_file first", "Do not use this to dump PCAP/images"],
      prerequisites: [],
      schema: readFileParamsSchema,
      parameters: [PATH, { name: "maxChars", type: "number", required: false, description: "Inline cap (default ~12k).", example: 8000 }],
      examples: [{ title: "statement", situation: "Open the challenge", args: { path: "challenge.txt" }, expectedSummary: "file read" }],
      output: { description: "File text, possibly truncated.", importantFields: ["text", "size"], interpretation: ["Truncated files should be searched with search_tool_output after writing or via a chunked read."] },
      failureModes: [{ code: "NOT_FOUND", meaning: "No such file.", recovery: "list_workspace first." }],
      suggestedNextTools: ["inspect_file", "parse_crypto_values"],
      cost: "CHEAP",
      tags: ["read", "text", "challenge"],
      run: wrap(readChallengeFile),
    },
    {
      name: "inspect_file",
      group: "WORKSPACE",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Cheap inspection: magic, size, sha256, entropy, image dims, pcap summary. Use on every attachment first.",
      whenToUse: ["First look at any new file", "After carving or extracting"],
      whenNotToUse: ["Not a full stego or crypto attack"],
      prerequisites: [],
      schema: inspectFileParamsSchema,
      parameters: [PATH],
      examples: [{ title: "attachment", situation: "Identify an input file", args: { path: "input/task.zip" }, expectedSummary: "inspection done" }],
      output: { description: "Magic/mime/entropy plus contextual next-tool hints.", importantFields: ["magic", "entropy", "hints"], interpretation: ["Follow hints via get_tool_help then execute_tool."] },
      failureModes: [{ code: "NOT_FOUND", meaning: "No such file.", recovery: "list_workspace." }],
      suggestedNextTools: ["extract_archive", "analyze_visual", "analyze_pcap_overview"],
      cost: "CHEAP",
      tags: ["magic", "file", "identify"],
      run: wrap(inspectFileTool),
    },
    {
      name: "write_work_file",
      group: "WORKSPACE",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Write a script or note. Bare names go under work/ (solve.py → work/solve.py).",
      whenToUse: ["Save a reproducible solve script", "Keep notes"],
      whenNotToUse: ["Do not overwrite input/"],
      prerequisites: [],
      schema: writeWorkFileParamsSchema,
      parameters: [
        { name: "path", type: "string", required: true, description: "Destination. Bare names land in work/.", example: "solve.py" },
        { name: "content", type: "string", required: true, description: "File contents." },
      ],
      examples: [{ title: "script", situation: "Save solve.py", args: { path: "solve.py", content: "print(1)\n" }, expectedSummary: "wrote" }],
      output: { description: "Path written.", importantFields: ["path"], interpretation: ["Then run_python with scriptPath=work/solve.py"] },
      failureModes: [{ code: "FS", meaning: "Could not write.", recovery: "Use a work/ path." }],
      suggestedNextTools: ["run_python"],
      cost: "CHEAP",
      tags: ["write", "script"],
      run: wrap(writeWorkFile),
    },
    {
      name: "run_python",
      group: "WORKSPACE",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Run Python in the workspace root. Escape hatch for custom logic — check discover_tools before reimplementing a standard attack.",
      whenToUse: ["Custom challenge logic", "Glue tool results", "Final solve.py"],
      whenNotToUse: ["Do not reimplement shipped RSA/XOR/PCAP tools before discover_tools"],
      prerequisites: [],
      schema: runPythonParamsSchema,
      parameters: [
        { name: "code", type: "string", required: false, description: "Inline snippet. cwd is workspace root." },
        { name: "scriptPath", type: "string", required: false, description: "Prefer work/solve.py" },
        { name: "args", type: "string[]", required: false, description: "argv after the script." },
        { name: "timeoutMs", type: "number", required: false, description: "Timeout, default tens of seconds." },
      ],
      examples: [{ title: "inline", situation: "List input/", args: { code: "import os; print(os.listdir('input'))" }, expectedSummary: "command finished" }],
      output: { description: "stdout/stderr. Long output is saved under results/.", importantFields: ["stdout", "fullOutputPath"], interpretation: ["Non-zero exit is not a flag. Search saved output if truncated."] },
      failureModes: [{ code: "EXIT", meaning: "Process failed or timed out.", recovery: "Read stderr; shrink the script." }],
      suggestedNextTools: ["search_tool_output", "submit_flag_candidate"],
      cost: "NORMAL",
      tags: ["python", "script", "escape"],
      run: (ctx, params, meta) => runPython(ctx, params, meta),
    },
    {
      name: "search_tool_output",
      group: "WORKSPACE",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Search a saved results/ file for a substring (flags, tokens).",
      whenToUse: ["Output was truncated", "Looking for flag{ in a long dump"],
      whenNotToUse: ["Do not search input binaries this way if inspect_file has not run"],
      prerequisites: ["A results/ or other workspace file"],
      schema: searchToolOutputParamsSchema,
      parameters: [
        PATH,
        { name: "query", type: "string", required: true, description: "Substring to find.", example: "flag{" },
        { name: "maxMatches", type: "number", required: false, description: "Cap matches." },
      ],
      examples: [{ title: "flag", situation: "Find flag in a dump", args: { path: "results/tool-0001.txt", query: "flag{" }, expectedSummary: "found" }],
      output: { description: "Match offsets and snippets.", importantFields: ["matches"], interpretation: ["No match means try another encoding, not repeat the same query."] },
      failureModes: [{ code: "NOT_FOUND", meaning: "File missing.", recovery: "Use the fullOutputPath from the previous tool." }],
      suggestedNextTools: ["read_tool_output_chunk"],
      cost: "CHEAP",
      tags: ["search", "grep", "results"],
      run: wrap(searchToolOutput),
    },
    {
      name: "read_tool_output_chunk",
      group: "WORKSPACE",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Read a window of a saved tool output file.",
      whenToUse: ["Paginate a long results/ file"],
      whenNotToUse: ["Small files can be read with read_challenge_file"],
      prerequisites: [],
      schema: readToolOutputChunkParamsSchema,
      parameters: [
        PATH,
        { name: "offset", type: "number", required: false, description: "Byte/char offset." },
        { name: "maxChars", type: "number", required: false, description: "Window size." },
      ],
      examples: [{ title: "page", situation: "Read the start of a dump", args: { path: "results/tool-0001.txt", offset: 0 }, expectedSummary: "chunk" }],
      output: { description: "A text window and total length.", importantFields: ["chunk", "totalLength"], interpretation: ["Advance offset by the chunk length."] },
      failureModes: [{ code: "NOT_FOUND", meaning: "File missing.", recovery: "Check results/ via list_workspace." }],
      suggestedNextTools: ["search_tool_output"],
      cost: "CHEAP",
      tags: ["read", "chunk", "results"],
      run: wrap(readToolOutputChunk),
    },
    {
      name: "record_hypothesis",
      group: "CONTROL",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Record a hypothesis the planner should track.",
      whenToUse: ["You have a concrete theory to test"],
      whenNotToUse: ["Do not record every random idea"],
      prerequisites: [],
      schema: hypothesisParamsSchema,
      parameters: [
        { name: "description", type: "string", required: true, description: "The hypothesis." },
        { name: "confidence", type: "number", required: false, description: "0..1" },
      ],
      examples: [{ title: "rsa", situation: "Suspect small e", args: { description: "textbook RSA e=3, m^e < n", confidence: 0.6 }, expectedSummary: "hypothesis recorded" }],
      output: { description: "Acknowledged hypothesis.", importantFields: ["description"], interpretation: ["Then pick a discriminating test via discover_tools."] },
      failureModes: [{ code: "VALIDATION", meaning: "description required.", recovery: "Write one sentence." }],
      suggestedNextTools: ["discover_tools", "report_progress"],
      cost: "CHEAP",
      tags: ["hypothesis", "plan"],
      run: wrap(recordHypothesis),
    },
    {
      name: "report_progress",
      group: "CONTROL",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Report progress, facts, and whether you are stalled.",
      whenToUse: ["Every few minutes or after a major discovery"],
      whenNotToUse: ["Not a substitute for submit_flag_candidate"],
      prerequisites: [],
      schema: reportProgressParamsSchema,
      parameters: [
        { name: "summary", type: "string", required: true, description: "What changed." },
        { name: "confidence", type: "number", required: true, description: "0..1" },
        { name: "progress", type: "SIGNIFICANT|MINOR|NONE", required: false, description: "How much moved." },
        { name: "stalled", type: "boolean", required: false, description: "True if repeating failed tests." },
      ],
      examples: [{ title: "update", situation: "Found trailing ZIP", args: { summary: "PNG has trailing ZIP", confidence: 0.5, progress: "SIGNIFICANT" }, expectedSummary: "progress reported" }],
      output: { description: "Acknowledged.", importantFields: ["acknowledged"], interpretation: ["Control plane uses this for scheduling."] },
      failureModes: [{ code: "VALIDATION", meaning: "summary+confidence required.", recovery: "Fill both." }],
      suggestedNextTools: ["discover_tools"],
      cost: "CHEAP",
      tags: ["progress", "status"],
      run: wrap(reportProgressTool),
    },
    {
      name: "submit_flag_candidate",
      group: "CONTROL",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Propose a flag. You cannot submit to the contest yourself — the control plane verifies.",
      whenToUse: ["You have a credible flag{...} or contest-shaped token"],
      whenNotToUse: ["Do not spray guesses", "Do not call execute_tool on this"],
      prerequisites: [],
      schema: submitFlagCandidateParamsSchema,
      parameters: [
        { name: "value", type: "string", required: true, description: "The flag, usually flag{...}." },
        { name: "confidence", type: "number", required: true, description: "0..1; auto-submit at >= 0.85" },
        { name: "reason", type: "string", required: true, description: "How you derived it." },
      ],
      examples: [{ title: "flag", situation: "Recovered plaintext", args: { value: "flag{demo}", confidence: 0.9, reason: "decoded trailing text" }, expectedSummary: "candidate submitted" }],
      output: { description: "Queued for verification.", importantFields: ["acknowledged"], interpretation: ["Wrong flags come back as evidence. Do not resubmit the same value."] },
      failureModes: [{ code: "VALIDATION", meaning: "value/confidence/reason required.", recovery: "Fill all three." }],
      suggestedNextTools: ["report_progress"],
      cost: "CHEAP",
      tags: ["flag", "submit"],
      run: wrap(submitFlagCandidateTool),
    },
    {
      name: "request_reflection",
      group: "CONTROL",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Ask for an independent reflection pass when stuck. Does not run tools itself.",
      whenToUse: ["Repeated NO_SIGNAL", "Wrong flag", "You are looping"],
      whenNotToUse: ["Not a first action", "Cannot be invoked via execute_tool"],
      prerequisites: [],
      schema: requestReflectionParamsSchema,
      parameters: [{ name: "reason", type: "string", required: true, description: "Why you are stuck." }],
      examples: [{ title: "stuck", situation: "Three empty experiments", args: { reason: "no_signal_streak on the same PNG" }, expectedSummary: "reflection requested" }],
      output: { description: "Reflection scheduled.", importantFields: ["acknowledged"], interpretation: ["Wait for HUMAN/REFLECTOR notes in the next inject."] },
      failureModes: [{ code: "VALIDATION", meaning: "reason required.", recovery: "Say what you already tried." }],
      suggestedNextTools: ["discover_tools"],
      cost: "NORMAL",
      tags: ["reflection", "stuck"],
      run: wrap(requestReflectionTool),
    },
    {
      name: "request_handoff",
      group: "CONTROL",
      domains: ["MISC", "CRYPTO"],
      exposure: "CORE",
      routerExecutable: false,
      summary: "Ask the control plane to hand the challenge to the other solver domain.",
      whenToUse: ["Misc file is actually RSA", "Crypto statement is a stego image"],
      whenNotToUse: ["Do not bounce back and forth", "Cannot be invoked via execute_tool"],
      prerequisites: [],
      schema: requestHandoffParamsSchema,
      parameters: [
        { name: "target", type: "MISC|CRYPTO", required: true, description: "Destination domain." },
        { name: "summary", type: "string", required: true, description: "Why." },
      ],
      examples: [{ title: "to crypto", situation: "Found n,e,c", args: { target: "CRYPTO", summary: "challenge.txt is textbook RSA" }, expectedSummary: "handoff requested" }],
      output: { description: "Handoff requested.", importantFields: ["acknowledged"], interpretation: ["A new solver session may start."] },
      failureModes: [{ code: "VALIDATION", meaning: "target must be MISC or CRYPTO.", recovery: "Pick one." }],
      suggestedNextTools: ["report_progress"],
      cost: "CHEAP",
      tags: ["handoff", "domain"],
      run: wrap(requestHandoffTool),
    },
  ];
  return tools;
}
