import {
  aesInspectSchema,
  analyzeRsaInstanceSchema,
  crtSchema,
  discreteLogSchema,
  extendedGcdSchema,
  factorIntegerSchema,
  frequencyAnalysisSchema,
  gcdSchema,
  integerRootSchema,
  lcgRecoverSchema,
  linearCongruenceSchema,
  lllReduceSchema,
  modInverseSchema,
  parseCryptoValuesSchema,
  rsaBasicDecryptSchema,
  rsaCommonModulusSchema,
  rsaFermatSchema,
  rsaHastadSchema,
  rsaSmallESchema,
  rsaWienerSchema,
  xorBytesSchema,
  xorKnownPlaintextSchema,
} from "@rio/domain";
import type { ToolDescriptor } from "./types.js";
import { analyzeRsaTool, parseCryptoValuesTool, rsaAttackTool } from "../semantic-tools.js";

function attack(name: string): ToolDescriptor["run"] {
  return (ctx, params) => rsaAttackTool(name, ctx, params);
}

const INT = "bigint-string";
const NOTE = "All cryptographic integers are strings (decimal or 0x hex). Never JSON numbers.";

export function cryptoTools(): ToolDescriptor[] {
  return [
    {
      name: "parse_crypto_values",
      group: "CRYPTO_PARSE",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Parse n/e/c/p/q and similar labels from challenge text. Does not attack.",
      whenToUse: ["Challenge text or a file contains n = ..., e = ..., c = ...", "Before any RSA attack"],
      whenNotToUse: ["Do not use this to decrypt", "Not a substitute for analyze_rsa_instance"],
      prerequisites: [],
      schema: parseCryptoValuesSchema,
      parameters: [
        { name: "text", type: "string", required: false, description: "Raw challenge text to parse." },
        { name: "path", type: "string", required: false, description: "File to read instead of text." },
      ],
      examples: [{ title: "text", situation: "Statement lists n,e,c", args: { text: "n=221 e=5 c=80" }, expectedSummary: "parsed" }],
      output: { description: "Map of parsed labels to integer strings.", importantFields: ["values"], interpretation: ["Feed values into analyze_rsa_instance. This tool never returns a flag."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need text or path.", recovery: "Pass the statement." }],
      suggestedNextTools: ["analyze_rsa_instance"],
      cost: "CHEAP",
      tags: ["parse", "n", "e", "c", "parameters"],
      run: (ctx, params) => parseCryptoValuesTool(ctx, params),
    },
    {
      name: "analyze_rsa_instance",
      group: "CRYPTO_RSA",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Analyze an RSA instance (n,e,c) and list cheap attack candidates. Does not decrypt.",
      whenToUse: ["You have n and e (and maybe c)", "Need to know which shipped attack to try"],
      whenNotToUse: ["Do not start with LLL", "Not an attack itself"],
      prerequisites: [NOTE],
      schema: analyzeRsaInstanceSchema,
      parameters: [
        { name: "n", type: INT, required: false, description: "Modulus as a string." },
        { name: "e", type: INT, required: false, description: "Public exponent as a string." },
        { name: "c", type: INT, required: false, description: "Ciphertext as a string." },
        { name: "text", type: "string", required: false, description: "Optional text to parse extra values from." },
        { name: "path", type: "string", required: false, description: "Optional file to parse." },
      ],
      examples: [{ title: "small", situation: "Tiny n, small e", args: { n: "100070063", e: "3", c: "8" }, expectedSummary: "RSA" }],
      output: { description: "bitLength, checks, attackCandidates, plus next-tool hints.", importantFields: ["attackCandidates", "hints"], interpretation: ["Call get_tool_help on the hinted attack, then execute_tool. Do not spray every RSA tool."] },
      failureModes: [{ code: "VALIDATION", meaning: "Integers must be strings.", recovery: "Quote n/e/c." }],
      suggestedNextTools: ["rsa_small_e", "rsa_fermat", "rsa_wiener", "factor_integer"],
      cost: "CHEAP",
      tags: ["rsa", "analyze", "attack", "candidates"],
      run: (ctx, params) => analyzeRsaTool(ctx, params),
    },
    {
      name: "rsa_small_e",
      group: "CRYPTO_RSA",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Textbook RSA small-exponent attack: recover m from c = m^e (optionally mod n) when e is tiny (typically 3) and m^e has not wrapped, or by trying small k*n + c roots.",
      whenToUse: ["e = 3 (or other tiny e)", "c may be a perfect e-th power", "analyze_rsa_instance listed SMALL_E"],
      whenNotToUse: ["Ordinary e=65537", "No ciphertext", "You only have n"],
      prerequisites: [NOTE, "Need c and e. n is optional."],
      schema: rsaSmallESchema,
      parameters: [
        { name: "c", type: INT, required: true, description: "Ciphertext integer string." },
        { name: "e", type: INT, required: true, description: "Public exponent, typically \"3\"." },
        { name: "n", type: INT, required: false, description: "Modulus. Omit when m^e < n (pure integer root)." },
      ],
      examples: [
        { title: "perfect cube", situation: "m^3 with no modulus", args: { c: "27", e: "3" }, expectedSummary: "m=" },
        { title: "not applicable", situation: "Missing c", args: { c: "1", e: "3", n: "221" }, expectedSummary: "m=" },
      ],
      output: { description: "Recovered plaintext integer m, or null.", importantFields: ["m"], interpretation: ["Convert m to bytes if it looks like a flag. Failure means the root is not exact / modular wrap — do not repeat the same params; consider Håstad or other RSA analysis."] },
      failureModes: [
        { code: "VALIDATION", meaning: "Need c and e as strings.", recovery: "Pass {c, e} or {c, e, n}." },
        { code: "CRYPTO", meaning: "Root not exact or wrap occurred.", recovery: "Do not retry the same args. Try rsa_hastad / analyze_rsa_instance." },
      ],
      suggestedNextTools: ["integer_root", "rsa_hastad", "analyze_rsa_instance"],
      cost: "CHEAP",
      tags: ["rsa", "small-e", "cube", "root"],
      run: attack("rsa_small_e"),
    },
    {
      name: "rsa_fermat",
      group: "CRYPTO_RSA",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Fermat factorization when p and q are very close. Input is only n.",
      whenToUse: ["p ≈ q", "analyze_rsa_instance listed FERMAT", "n = p*q with close primes"],
      whenNotToUse: ["Uniform random primes far apart", "You only have e,c", "Do not use as a general factorizer"],
      prerequisites: [NOTE],
      schema: rsaFermatSchema,
      parameters: [{ name: "n", type: INT, required: true, description: "RSA modulus." }],
      examples: [
        { title: "close primes", situation: "10007*10009", args: { n: "100160063" }, expectedSummary: "p=" },
        { title: "not close", situation: "Random-looking n will fail quickly", args: { n: "221" }, expectedSummary: "p=" },
      ],
      output: { description: "p and q if found.", importantFields: ["p", "q"], interpretation: ["Then rsa_basic_decrypt with p,q,n,c."] },
      failureModes: [{ code: "VALIDATION", meaning: "n required.", recovery: "Pass n as a string." }],
      suggestedNextTools: ["rsa_basic_decrypt", "factor_integer"],
      cost: "NORMAL",
      tags: ["rsa", "fermat", "close", "primes", "factor"],
      run: attack("rsa_fermat"),
    },
    {
      name: "rsa_wiener",
      group: "CRYPTO_RSA",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Wiener attack: recover small private exponent d from n,e.",
      whenToUse: ["known n,e", "d suspected unusually small", "analyze_rsa_instance listed WIENER"],
      whenNotToUse: ["Ordinary random RSA", "No n/e", "Only p,q close (use Fermat instead)"],
      prerequisites: [NOTE],
      schema: rsaWienerSchema,
      parameters: [
        { name: "n", type: INT, required: true, description: "Modulus." },
        { name: "e", type: INT, required: true, description: "Public exponent (usually large when d is small)." },
      ],
      examples: [{ title: "small d", situation: "Constructed small-d instance", args: { n: "2430101", e: "17993" }, expectedSummary: "d=" }],
      output: { description: "d or null.", importantFields: ["d"], interpretation: ["If d is found, decrypt with rsa_basic_decrypt or Python."] },
      failureModes: [{ code: "VALIDATION", meaning: "n and e required.", recovery: "Pass both as strings." }],
      suggestedNextTools: ["rsa_basic_decrypt", "analyze_rsa_instance"],
      cost: "NORMAL",
      tags: ["rsa", "wiener", "small", "d"],
      run: attack("rsa_wiener"),
    },
    {
      name: "rsa_common_modulus",
      group: "CRYPTO_RSA",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Recover m when the same RSA modulus and the same plaintext were used with two different coprime public exponents.",
      whenToUse: ["Two ciphertexts represent the same plaintext", "Both use the same modulus n", "Public exponents e1 and e2 are usually coprime"],
      whenNotToUse: ["Different plaintexts", "Different moduli", "Only one ciphertext/exponent pair"],
      prerequisites: [NOTE, "Need n, e1, c1, e2, c2"],
      schema: rsaCommonModulusSchema,
      parameters: [
        { name: "n", type: INT, required: true, description: "Shared RSA modulus." },
        { name: "e1", type: INT, required: true, description: "First public exponent." },
        { name: "c1", type: INT, required: true, description: "Ciphertext under e1." },
        { name: "e2", type: INT, required: true, description: "Second public exponent." },
        { name: "c2", type: INT, required: true, description: "Ciphertext under e2." },
      ],
      examples: [
        { title: "same n two e", situation: "Same m encrypted with e=3 and e=5", args: { n: "221", e1: "3", c1: "80", e2: "5", c2: "163" }, expectedSummary: "m=" },
        { title: "wrong shape", situation: "This example is the valid contract — do not pass remainders[]", args: { n: "221", e1: "3", c1: "1", e2: "5", c2: "1" }, expectedSummary: "m=" },
      ],
      output: { description: "Recovered plaintext integer m or null.", importantFields: ["m"], interpretation: ["Failure usually means the common-modulus assumptions do not hold (different m, gcd(e1,e2)≠1, or different n)."] },
      failureModes: [
        { code: "TOOL_ARGUMENT_INVALID", meaning: "Missing n/e1/c1/e2/c2.", recovery: "Pass all five as strings." },
        { code: "CRYPTO", meaning: "Assumptions failed.", recovery: "Check same n, same m, coprime e." },
      ],
      suggestedNextTools: ["integer_root", "analyze_rsa_instance"],
      cost: "CHEAP",
      tags: ["rsa", "common", "modulus", "same", "n", "two", "exponents"],
      run: attack("rsa_common_modulus"),
    },
    {
      name: "rsa_hastad",
      group: "CRYPTO_RSA",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Håstad broadcast: same plaintext, same small e, different pairwise-coprime moduli. This implementation takes exactly 3 (n,c) pairs and e.",
      whenToUse: ["Same plaintext encrypted to several recipients", "Same small e (typically 3)", "At least e pairwise-coprime moduli"],
      whenNotToUse: ["Same modulus (use rsa_common_modulus)", "Different plaintexts", "Only one (n,c)"],
      prerequisites: [NOTE, "Currently exactly 3 pairs: n1,c1,n2,c2,n3,c3"],
      schema: rsaHastadSchema,
      parameters: [
        { name: "e", type: INT, required: true, description: "Shared small exponent, usually \"3\"." },
        { name: "n1", type: INT, required: true, description: "First modulus." },
        { name: "c1", type: INT, required: true, description: "First ciphertext." },
        { name: "n2", type: INT, required: true, description: "Second modulus." },
        { name: "c2", type: INT, required: true, description: "Second ciphertext." },
        { name: "n3", type: INT, required: true, description: "Third modulus." },
        { name: "c3", type: INT, required: true, description: "Third ciphertext." },
      ],
      examples: [{ title: "e=3 three moduli", situation: "Broadcast e=3", args: { e: "3", n1: "221", c1: "8", n2: "323", c2: "8", n3: "437", c3: "8" }, expectedSummary: "m=" }],
      output: { description: "m or null.", importantFields: ["m"], interpretation: ["Needs ≥ e pairs. This tool accepts exactly 3 pairs."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need e and three n/c pairs.", recovery: "Pass e,n1,c1,n2,c2,n3,c3." }],
      suggestedNextTools: ["rsa_small_e", "crt"],
      cost: "NORMAL",
      tags: ["rsa", "hastad", "broadcast", "crt"],
      run: attack("rsa_hastad"),
    },
    {
      name: "rsa_basic_decrypt",
      group: "CRYPTO_RSA",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Decrypt textbook RSA if n factors or p,q are known.",
      whenToUse: ["You have n,c and either factors or p,q", "After fermat/factor_integer"],
      whenNotToUse: ["Do not call this hoping it will break strong RSA"],
      prerequisites: [NOTE],
      schema: rsaBasicDecryptSchema,
      parameters: [
        { name: "n", type: INT, required: true, description: "Modulus." },
        { name: "c", type: INT, required: true, description: "Ciphertext." },
        { name: "e", type: INT, required: false, description: "Public exponent, default 65537." },
        { name: "p", type: INT, required: false, description: "Known prime factor." },
        { name: "q", type: INT, required: false, description: "Known prime factor." },
      ],
      examples: [{ title: "known factors", situation: "n=221=13*17, e=5, c=80", args: { n: "221", c: "80", e: "5", p: "13", q: "17" }, expectedSummary: "m=" }],
      output: { description: "m or null.", importantFields: ["m"], interpretation: ["Convert m to bytes for the flag."] },
      failureModes: [{ code: "VALIDATION", meaning: "n and c required.", recovery: "Pass n,c as strings." }],
      suggestedNextTools: ["factor_integer"],
      cost: "CHEAP",
      tags: ["rsa", "decrypt", "d"],
      run: attack("rsa_basic_decrypt"),
    },
    {
      name: "factor_integer",
      group: "CRYPTO_NUMBER_THEORY",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Factor a (small) integer with trial division / Pollard Rho. Not a general NFS.",
      whenToUse: ["n has < ~80 bits", "analyze_rsa_instance listed FACTOR"],
      whenNotToUse: ["1024-bit contest n without extra structure"],
      prerequisites: [NOTE],
      schema: factorIntegerSchema,
      parameters: [{ name: "n", type: INT, required: true, description: "Integer to factor." }],
      examples: [{ title: "small", situation: "221=13*17", args: { n: "221" }, expectedSummary: "factors" }],
      output: { description: "Factor list.", importantFields: ["factors"], interpretation: ["Use factors as p,q for rsa_basic_decrypt."] },
      failureModes: [{ code: "VALIDATION", meaning: "n required.", recovery: "Pass n as a string." }],
      suggestedNextTools: ["rsa_basic_decrypt", "rsa_fermat"],
      cost: "NORMAL",
      tags: ["factor", "integer", "rho"],
      run: attack("factor_integer"),
    },
    {
      name: "integer_root",
      group: "CRYPTO_NUMBER_THEORY",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Integer e-th root of c. Reports whether the root is exact.",
      whenToUse: ["Need ∛c or k-th root", "small-e without modulus"],
      whenNotToUse: ["Not a modular root"],
      prerequisites: [NOTE],
      schema: integerRootSchema,
      parameters: [
        { name: "c", type: INT, required: true, description: "Radicand." },
        { name: "e", type: INT, required: true, description: "Root degree, e.g. \"3\"." },
      ],
      examples: [{ title: "cube", situation: "27 = 3^3", args: { c: "27", e: "3" }, expectedSummary: "root=" }],
      output: { description: "root and exact flag.", importantFields: ["root", "exact"], interpretation: ["exact=false means c is not a perfect power."] },
      failureModes: [{ code: "VALIDATION", meaning: "c and e required.", recovery: "Pass both as strings." }],
      suggestedNextTools: ["rsa_small_e"],
      cost: "CHEAP",
      tags: ["root", "cube", "integer"],
      run: attack("integer_root"),
    },
    {
      name: "mod_inverse",
      group: "CRYPTO_NUMBER_THEORY",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Modular inverse: find x with a*x ≡ 1 (mod m).",
      whenToUse: ["Need a^{-1} mod m", "CRT / affine / RSA d pieces"],
      whenNotToUse: ["gcd(a,m)≠1 — there is no inverse"],
      prerequisites: [NOTE],
      schema: modInverseSchema,
      parameters: [
        { name: "a", type: INT, required: true, description: "Value to invert." },
        { name: "m", type: INT, required: true, description: "Modulus." },
      ],
      examples: [{ title: "inv", situation: "3 inverse mod 10 does not exist; 3 mod 10 wait 3 vs 11", args: { a: "3", m: "11" }, expectedSummary: "inv=" }],
      output: { description: "inverse or null.", importantFields: ["inverse"], interpretation: ["null means gcd≠1."] },
      failureModes: [{ code: "VALIDATION", meaning: "a and m required.", recovery: "Pass a,m as strings." }],
      suggestedNextTools: ["gcd", "extended_gcd"],
      cost: "CHEAP",
      tags: ["inverse", "mod", "egcd"],
      run: attack("mod_inverse"),
    },
    {
      name: "gcd",
      group: "CRYPTO_NUMBER_THEORY",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Greatest common divisor of two integers a and b.",
      whenToUse: ["Shared factors between moduli", "Any number-theory step"],
      whenNotToUse: ["Not an RSA decrypt"],
      prerequisites: [NOTE],
      schema: gcdSchema,
      parameters: [
        { name: "a", type: INT, required: true, description: "First integer." },
        { name: "b", type: INT, required: true, description: "Second integer." },
      ],
      examples: [{ title: "gcd", situation: "12 and 18", args: { a: "12", b: "18" }, expectedSummary: "gcd=" }],
      output: { description: "gcd as a string.", importantFields: ["gcd"], interpretation: ["gcd>1 of two n's is a factor."] },
      failureModes: [{ code: "VALIDATION", meaning: "a and b required.", recovery: "Pass a,b as strings." }],
      suggestedNextTools: ["extended_gcd", "factor_integer"],
      cost: "CHEAP",
      tags: ["gcd", "factor", "shared"],
      run: attack("gcd"),
    },
    {
      name: "extended_gcd",
      group: "CRYPTO_NUMBER_THEORY",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Extended gcd: g, x, y with a*x + b*y = g.",
      whenToUse: ["Need Bézout coefficients", "Common-modulus internals"],
      whenNotToUse: ["Plain gcd is enough if you only need the divisor"],
      prerequisites: [NOTE],
      schema: extendedGcdSchema,
      parameters: [
        { name: "a", type: INT, required: true, description: "First integer." },
        { name: "b", type: INT, required: true, description: "Second integer." },
      ],
      examples: [{ title: "egcd", situation: "30 and 12", args: { a: "30", b: "12" }, expectedSummary: "g=" }],
      output: { description: "g, x, y.", importantFields: ["g", "x", "y"], interpretation: ["g is gcd(a,b)."] },
      failureModes: [{ code: "VALIDATION", meaning: "a and b required.", recovery: "Pass a,b as strings." }],
      suggestedNextTools: ["mod_inverse", "crt"],
      cost: "CHEAP",
      tags: ["egcd", "bezout"],
      run: attack("extended_gcd"),
    },
    {
      name: "crt",
      group: "CRYPTO_NUMBER_THEORY",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Chinese Remainder Theorem for exactly two congruences: x ≡ a (mod m), x ≡ b (mod m2). This implementation does not accept remainders[]/moduli[] arrays.",
      whenToUse: ["Two congruences", "Håstad pieces", "RSA with known p,q residues"],
      whenNotToUse: ["More than two congruences — use run_python", "Do not pass remainders/moduli arrays"],
      prerequisites: [NOTE, "Exactly two pairs: (a,m) and (b,m2). m and m2 should be coprime."],
      schema: crtSchema,
      parameters: [
        { name: "a", type: INT, required: true, description: "First remainder. x ≡ a (mod m)." },
        { name: "m", type: INT, required: true, description: "First modulus." },
        { name: "b", type: INT, required: true, description: "Second remainder. x ≡ b (mod m2)." },
        { name: "m2", type: INT, required: true, description: "Second modulus." },
      ],
      examples: [
        { title: "two congruences", situation: "x≡2 mod 3, x≡3 mod 5", args: { a: "2", m: "3", b: "3", m2: "5" }, expectedSummary: "x=" },
        { title: "not arrays", situation: "Do not pass remainders/moduli", args: { a: "0", m: "5", b: "1", m2: "2" }, expectedSummary: "x=" },
      ],
      output: { description: "x or null if inconsistent / not coprime in this helper.", importantFields: ["x"], interpretation: ["Only two congruences. For e=3 Håstad use rsa_hastad instead."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need a,m,b,m2 — not arrays.", recovery: "Pass the four strings." }],
      suggestedNextTools: ["rsa_hastad", "solve_linear_congruence"],
      cost: "CHEAP",
      tags: ["crt", "congruence", "remainder"],
      run: attack("crt"),
    },
    {
      name: "solve_linear_congruence",
      group: "CRYPTO_NUMBER_THEORY",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Solve ax ≡ b (mod m). Returns one particular solution and the reduced modulus.",
      whenToUse: ["Linear congruence", "Affine cipher key recovery"],
      whenNotToUse: ["Not a discrete log", "Not CRT"],
      prerequisites: [NOTE],
      schema: linearCongruenceSchema,
      parameters: [
        { name: "a", type: INT, required: true, description: "Coefficient." },
        { name: "b", type: INT, required: true, description: "Right-hand side." },
        { name: "m", type: INT, required: true, description: "Modulus." },
      ],
      examples: [{ title: "3x≡4 mod 7", situation: "Tiny congruence", args: { a: "3", b: "4", m: "7" }, expectedSummary: "x=" }],
      output: { description: "x and reduced modulus, or no solution.", importantFields: ["x", "modulus"], interpretation: ["General solution is x + k*modulus."] },
      failureModes: [{ code: "VALIDATION", meaning: "a,b,m required.", recovery: "Pass three strings." }],
      suggestedNextTools: ["mod_inverse", "crt"],
      cost: "CHEAP",
      tags: ["linear", "congruence", "ax", "mod"],
      run: attack("solve_linear_congruence"),
    },
    {
      name: "discrete_log_if_small",
      group: "CRYPTO_NUMBER_THEORY",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Baby-step giant-step discrete log: find small x with g^x ≡ h (mod m).",
      whenToUse: ["Small order / small x", "g,h,m given"],
      whenNotToUse: ["Full-size DH", "x is huge"],
      prerequisites: [NOTE, "Parameters are g, h, m — not a/b."],
      schema: discreteLogSchema,
      parameters: [
        { name: "g", type: INT, required: true, description: "Generator / base." },
        { name: "h", type: INT, required: true, description: "Target, g^x mod m." },
        { name: "m", type: INT, required: true, description: "Modulus." },
      ],
      examples: [{ title: "tiny", situation: "2^x ≡ 14 mod 101", args: { g: "2", h: "14", m: "101" }, expectedSummary: "x=" }],
      output: { description: "x or null if not small.", importantFields: ["x"], interpretation: ["null means no small x. Do not retry the same triple."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need g,h,m (not a,b).", recovery: "Pass g,h,m as strings." }],
      suggestedNextTools: ["run_python"],
      cost: "NORMAL",
      tags: ["dlog", "discrete", "log", "bsgs"],
      run: attack("discrete_log_if_small"),
    },
    {
      name: "lcg_recover",
      group: "CRYPTO_PRNG",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Recover LCG a,c from a sequence of samples (glibc-style, known modulus 2^32 by default).",
      whenToUse: ["PRNG outputs listed", "Need next numbers"],
      whenNotToUse: ["MT19937 / other PRNGs", "Fewer than 3 samples"],
      prerequisites: ["samples is a comma/whitespace separated list of integer strings"],
      schema: lcgRecoverSchema,
      parameters: [{ name: "samples", type: "string", required: true, description: "Whitespace or comma separated integers.", example: "42, 1664567, 1, 2" }],
      examples: [{ title: "four samples", situation: "Known LCG stream", args: { samples: "7 1664532 1013904246 42" }, expectedSummary: "a=" }],
      output: { description: "a,c if recovered.", importantFields: ["a", "c"], interpretation: ["Need enough samples. 2 is not enough."] },
      failureModes: [{ code: "VALIDATION", meaning: "samples required.", recovery: "Pass a string of integers." }],
      suggestedNextTools: ["request_specialist"],
      cost: "CHEAP",
      tags: ["lcg", "prng", "rand"],
      run: attack("lcg_recover"),
    },
    {
      name: "aes_inspect",
      group: "CRYPTO_SYMMETRIC",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Guess AES mode from ciphertext layout (block alignment, ECB repetition). Does not decrypt.",
      whenToUse: ["HEX blob or file that might be AES", "Looking for ECB vs CBC"],
      whenNotToUse: ["Not a key-recovery tool"],
      prerequisites: [],
      schema: aesInspectSchema,
      parameters: [
        { name: "path", type: "string", required: false, description: "File of raw ciphertext." },
        { name: "text", type: "string", required: false, description: "HEX ciphertext." },
      ],
      examples: [{ title: "hex", situation: "Aligned hex", args: { text: "00112233445566778899aabbccddeeff" }, expectedSummary: "AES" }],
      output: { description: "likelyMode and notes.", importantFields: ["likelyMode"], interpretation: ["ECB with repeating blocks is the usual CTF gift."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need path or HEX text.", recovery: "Pass one of them." }],
      suggestedNextTools: ["xor_bytes", "run_python"],
      cost: "CHEAP",
      tags: ["aes", "ecb", "cbc", "mode"],
      run: attack("aes_inspect"),
    },
    {
      name: "frequency_analysis",
      group: "CRYPTO_XOR_CLASSICAL",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Letter frequency / Caesar shift hint on text.",
      whenToUse: ["Classical cipher / Caesar / monoalphabetic"],
      whenNotToUse: ["Modern AES/RSA blobs"],
      prerequisites: [],
      schema: frequencyAnalysisSchema,
      parameters: [
        { name: "text", type: "string", required: false, description: "Ciphertext text." },
        { name: "path", type: "string", required: false, description: "File to read as text." },
      ],
      examples: [{ title: "caesar", situation: "Shifted English", args: { text: "Wklv lv d iodj" }, expectedSummary: "caesar" }],
      output: { description: "likelyCaesar and frequencies.", importantFields: ["likelyCaesar"], interpretation: ["Try the hinted shift in Python."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need text or path.", recovery: "Pass the ciphertext." }],
      suggestedNextTools: ["run_python"],
      cost: "CHEAP",
      tags: ["frequency", "caesar", "classical"],
      run: attack("frequency_analysis"),
    },
    {
      name: "xor_bytes",
      group: "CRYPTO_XOR_CLASSICAL",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "XOR hex data with a UTF-8 key. a is HEX ciphertext/data; b or key is a UTF-8 string (NOT hex).",
      whenToUse: ["Single-byte or repeating-key XOR", "You already know the key as text"],
      whenNotToUse: ["Do not pass b as hex unless the key really is those ASCII hex characters", "Not for AES"],
      prerequisites: ["a = HEX data. b/key = UTF-8 key bytes."],
      schema: xorBytesSchema,
      parameters: [
        { name: "a", type: "hex-string", required: true, description: "Data as hex (no 0x).", acceptedFormats: ["68656c6c6f"], example: "00ff11" },
        { name: "b", type: "utf8-string", required: false, description: "UTF-8 key. Repeats to the length of a." },
        { name: "key", type: "utf8-string", required: false, description: "Alias for b." },
      ],
      examples: [
        { title: "xor key", situation: "hex data XOR text key", args: { a: "000000", key: "A" }, expectedSummary: "xor" },
        { title: "wrong encoding", situation: "b is UTF-8, not hex", args: { a: "41", b: "A" }, expectedSummary: "xor" },
      ],
      output: { description: "XOR result as hex.", importantFields: ["hex"], interpretation: ["Decode hex to bytes/text. If garbage, the key encoding was probably wrong."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need a plus b or key.", recovery: "a=hex, key=utf8." }],
      suggestedNextTools: ["xor_known_plaintext", "frequency_analysis"],
      cost: "CHEAP",
      tags: ["xor", "repeating", "key"],
      run: attack("xor_bytes"),
    },
    {
      name: "xor_known_plaintext",
      group: "CRYPTO_XOR_CLASSICAL",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Recover a keystream by XORing HEX ciphertext with a UTF-8 known plaintext prefix (often flag{).",
      whenToUse: ["You know the first bytes (flag{)", "Many-time pad"],
      whenNotToUse: ["No known plaintext"],
      prerequisites: ["c = HEX ciphertext. p or m = UTF-8 plaintext."],
      schema: xorKnownPlaintextSchema,
      parameters: [
        { name: "c", type: "hex-string", required: true, description: "Ciphertext hex." },
        { name: "p", type: "utf8-string", required: false, description: "Known plaintext UTF-8." },
        { name: "m", type: "utf8-string", required: false, description: "Alias for p." },
      ],
      examples: [{ title: "flag{", situation: "Known prefix", args: { c: "0000000000", p: "flag{" }, expectedSummary: "keystream" }],
      output: { description: "Keystream hex of length min(c,p).", importantFields: ["hex"], interpretation: ["Reuse the keystream on other ciphertexts."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need c and p/m.", recovery: "c=hex, p=utf8." }],
      suggestedNextTools: ["xor_bytes"],
      cost: "CHEAP",
      tags: ["xor", "crib", "known", "plaintext"],
      run: attack("xor_known_plaintext"),
    },
    {
      name: "lll_reduce",
      group: "CRYPTO_ADVANCED_MATH",
      domains: ["CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "LLL-reduce an integer lattice basis. It only reduces the matrix — it does not automatically solve an arbitrary lattice CTF. You must construct the lattice.",
      whenToUse: ["You already built an integer basis", "Coppersmith / knapsack / stereotyped RSA after you know the lattice"],
      whenNotToUse: ["Do not dump a random matrix because the challenge is Crypto", "Not a substitute for Fermat/Wiener/small-e"],
      prerequisites: ["matrix = JSON [[..],[..]] or whitespace rows of integers. Agent still must know how to construct the lattice."],
      schema: lllReduceSchema,
      parameters: [{ name: "matrix", type: "string", required: true, description: "JSON integer matrix or whitespace rows.", example: "[[1,1,1],[-1,0,2],[3,5,6]]" }],
      examples: [{ title: "3x3", situation: "Tiny basis", args: { matrix: "[[1,1,1],[-1,0,2],[3,5,6]]" }, expectedSummary: "lll" }],
      output: { description: "Reduced basis and backend (local / sage / fpylll).", importantFields: ["matrix", "backend"], interpretation: ["You still have to read the short vectors. backend tells you who reduced it."] },
      failureModes: [
        { code: "VALIDATION", meaning: "Need matrix string.", recovery: "Pass JSON [[ints]]." },
        { code: "BACKEND_UNAVAILABLE", meaning: "Only if a forced remote backend is missing.", recovery: "Local backend is the default." },
      ],
      suggestedNextTools: ["run_python", "analyze_rsa_instance"],
      cost: "EXPENSIVE",
      tags: ["lll", "lattice", "fplll", "coppersmith"],
      run: attack("lll_reduce"),
    },
  ];
}
