import { carveSchema, extractArchiveParamsSchema, followTcpStreamSchema, pathOnlySchema, specialistParamsSchema } from "@rio/domain";
import type { ToolDescriptor } from "./types.js";
import { extractArchive } from "../tools.js";
import {
  analyzePcapOverviewTool,
  carveFilesTool,
  extractDnsActivityTool,
  extractHttpObjectsTool,
  extractStringsSummaryTool,
  followTcpStreamTool,
  inspectMetadataTool,
  requestSpecialistTool,
  scanEmbeddedSignaturesTool,
  scanTrailingDataTool,
} from "../semantic-tools.js";

const PATH = { name: "path", type: "string", required: true, description: "Workspace-relative file.", acceptedFormats: ["input/a.png", "artifacts/extracted/x"] };
const FORCE = { name: "force", type: "boolean", required: false, description: "Bypass ALREADY_TESTED and re-run." };

function wrap(run: ToolDescriptor["run"]): ToolDescriptor["run"] {
  return (ctx, params, meta) => Promise.resolve(run(ctx, params, meta));
}

export function miscTools(): ToolDescriptor[] {
  return [
    {
      name: "extract_archive",
      group: "MISC_ARCHIVE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Extract a zip (or gunzip) into artifacts/ with zip-bomb limits.",
      whenToUse: ["inspect_file says ZIP/GZIP", "Nested archives after a first extract"],
      whenNotToUse: ["Not for raw images or PCAPs", "Not a general unrar if the magic is not ZIP/GZIP"],
      prerequisites: ["A ZIP or GZIP file in the workspace"],
      schema: extractArchiveParamsSchema,
      parameters: [
        PATH,
        { name: "destPath", type: "string", required: false, description: "Default artifacts/extracted" },
        { name: "maxDepth", type: "number", required: false, description: "Nested zip depth, max 8" },
      ],
      examples: [{ title: "zip", situation: "input/task.zip", args: { path: "input/task.zip" }, expectedSummary: "extracted" }],
      output: { description: "Extracted entry list and nested-archive flags.", importantFields: ["dest", "count", "nested"], interpretation: ["Inspect each extracted file. Nested archives need another extract."] },
      failureModes: [{ code: "UNSUPPORTED_ARCHIVE", meaning: "Not ZIP/GZIP.", recovery: "inspect_file; maybe scan_embedded_signatures." }],
      suggestedNextTools: ["inspect_file", "scan_trailing_data"],
      cost: "NORMAL",
      tags: ["zip", "archive", "unzip", "gzip"],
      run: wrap(extractArchive),
    },
    {
      name: "inspect_metadata",
      group: "MISC_FILE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Extract container metadata (PNG tEXt/iTXt/tIME, JPEG COM/Exif presence, PDF info, ZIP comment).",
      whenToUse: ["PNG/JPEG/PDF/ZIP that may hide clues in metadata", "Before heavy visual analysis"],
      whenNotToUse: ["Not a substitute for analyze_visual or carving"],
      prerequisites: ["A file in the workspace"],
      schema: pathOnlySchema,
      parameters: [PATH, FORCE],
      examples: [{ title: "png", situation: "PNG may have tEXt comment", args: { path: "input/a.png" }, expectedSummary: "metadata" }],
      output: { description: "magic/format plus key/value metadata fields.", importantFields: ["fields", "magic"], interpretation: ["Text chunks may contain flags or passwords."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["analyze_visual", "scan_trailing_data"],
      cost: "CHEAP",
      tags: ["metadata", "exif", "tEXt", "comment"],
      run: wrap(inspectMetadataTool),
    },
    {
      name: "scan_trailing_data",
      group: "MISC_FILE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Find bytes after PNG IEND / JPEG FFD9 / GIF trailer / ZIP EOCD.",
      whenToUse: ["PNG/JPEG/GIF/ZIP that may hide an appended payload", "inspect_file hinted trailing bytes"],
      whenNotToUse: ["Not useful on raw text or already-carved slices"],
      prerequisites: ["A container file"],
      schema: pathOnlySchema,
      parameters: [PATH, FORCE],
      examples: [{ title: "png", situation: "PNG larger than its pixels suggest", args: { path: "input/a.png" }, expectedSummary: "trailing" }],
      output: { description: "Whether trailing bytes exist, offset, size, magic.", importantFields: ["hasTrailingData", "offset", "bytes", "magic"], interpretation: ["If true, carve_files at that offset."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["carve_files", "scan_embedded_signatures"],
      cost: "CHEAP",
      tags: ["trailing", "iend", "stego", "appended"],
      run: wrap(scanTrailingDataTool),
    },
    {
      name: "scan_embedded_signatures",
      group: "MISC_FILE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Locate ZIP/PNG/JPEG/PDF/PE/ELF/GZIP/7z/RAR/SQLite magic offsets inside a blob.",
      whenToUse: ["Unknown binary", "High entropy file that may contain another file"],
      whenNotToUse: ["Already-identified small text files"],
      prerequisites: [],
      schema: pathOnlySchema,
      parameters: [PATH, FORCE],
      examples: [{ title: "blob", situation: "random.bin may hide a zip", args: { path: "input/blob.bin" }, expectedSummary: "signatures" }],
      output: { description: "List of {offset,type,confidence}.", importantFields: ["hits"], interpretation: ["Carve from a hit offset."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["carve_files"],
      cost: "CHEAP",
      tags: ["magic", "binwalk", "embedded", "signature"],
      run: wrap(scanEmbeddedSignaturesTool),
    },
    {
      name: "extract_strings_summary",
      group: "MISC_FILE",
      domains: ["MISC", "CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Summarize interesting strings (flags, URLs, base64). Not a full dump.",
      whenToUse: ["Any binary or unknown file after inspect", "Look for flag-like tokens"],
      whenNotToUse: ["Not a replacement for decode/crypto attacks"],
      prerequisites: [],
      schema: pathOnlySchema,
      parameters: [PATH, FORCE],
      examples: [{ title: "bin", situation: "strings of a blob", args: { path: "input/a.bin" }, expectedSummary: "strings" }],
      output: { description: "Count plus flag-like / url / b64 highlights.", importantFields: ["flagLike", "count"], interpretation: ["flagLike hits are candidates; still verify."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["submit_flag_candidate", "parse_crypto_values"],
      cost: "CHEAP",
      tags: ["strings", "flag", "ascii"],
      run: wrap(extractStringsSummaryTool),
    },
    {
      name: "analyze_pcap_overview",
      group: "MISC_PCAP",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "PCAP packet/protocol/HTTP/DNS/conversation overview.",
      whenToUse: ["inspect_file says PCAP", "Need protocols before carving streams"],
      whenNotToUse: ["Not for images or zip files"],
      prerequisites: ["A PCAP file"],
      schema: pathOnlySchema,
      parameters: [PATH, FORCE],
      examples: [{ title: "pcap", situation: "First look at capture.pcap", args: { path: "input/capture.pcap" }, expectedSummary: "pcap" }],
      output: { description: "Packet counts, HTTP requests, DNS names.", importantFields: ["packetCount", "httpRequests", "dnsNames"], interpretation: ["Follow HTTP objects or DNS next."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["extract_http_objects", "extract_dns_activity", "follow_tcp_stream"],
      cost: "NORMAL",
      tags: ["pcap", "network", "packets"],
      run: wrap(analyzePcapOverviewTool),
    },
    {
      name: "follow_tcp_stream",
      group: "MISC_PCAP",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Reassemble one TCP stream from a PCAP (by index or endpoints/ports).",
      whenToUse: ["Overview showed TCP conversations", "Need the raw stream bytes / ASCII"],
      whenNotToUse: ["UDP-only captures", "Prefer extract_http_objects when the payload is clearly HTTP"],
      prerequisites: ["A PCAP with TCP"],
      schema: followTcpStreamSchema,
      parameters: [
        PATH,
        { name: "streamIndex", type: "number", required: false, description: "0-based stream index from availableStreams." },
        { name: "src", type: "string", required: false, description: "Optional source IP filter." },
        { name: "dst", type: "string", required: false, description: "Optional destination IP filter." },
        { name: "sport", type: "number", required: false, description: "Optional source port." },
        { name: "dport", type: "number", required: false, description: "Optional destination port." },
        { name: "maxBytes", type: "number", required: false, description: "Cap reassembled bytes (default 64KiB)." },
        FORCE,
      ],
      examples: [{ title: "first stream", situation: "Follow stream 0", args: { path: "input/capture.pcap", streamIndex: 0 }, expectedSummary: "tcp stream" }],
      output: { description: "Stream key, segment previews, reassembled ASCII/HEX.", importantFields: ["streamKey", "reassembledAscii", "availableStreams"], interpretation: ["Look for flags/HTTP in reassembledAscii; try another streamIndex if empty."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["extract_http_objects", "extract_strings_summary", "carve_files"],
      cost: "NORMAL",
      tags: ["tcp", "stream", "follow", "pcap", "reassemble"],
      run: wrap(followTcpStreamTool),
    },
    {
      name: "extract_http_objects",
      group: "MISC_PCAP",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "List HTTP requests found in a PCAP.",
      whenToUse: ["Overview showed HTTP", "Looking for downloaded files or flags in bodies"],
      whenNotToUse: ["No HTTP in the capture"],
      prerequisites: ["PCAP with HTTP"],
      schema: pathOnlySchema,
      parameters: [PATH, FORCE],
      examples: [{ title: "http", situation: "Pull HTTP from capture", args: { path: "input/capture.pcap" }, expectedSummary: "HTTP" }],
      output: { description: "HTTP request list.", importantFields: ["requests"], interpretation: ["Bodies may contain flags or files."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["extract_dns_activity", "carve_files"],
      cost: "NORMAL",
      tags: ["http", "pcap", "objects"],
      run: wrap(extractHttpObjectsTool),
    },
    {
      name: "extract_dns_activity",
      group: "MISC_PCAP",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "List DNS names from a PCAP.",
      whenToUse: ["Overview showed DNS", "Suspected DNS exfil / encoded names"],
      whenNotToUse: ["No DNS in the capture"],
      prerequisites: ["PCAP"],
      schema: pathOnlySchema,
      parameters: [PATH, FORCE],
      examples: [{ title: "dns", situation: "Names in capture", args: { path: "input/capture.pcap" }, expectedSummary: "DNS" }],
      output: { description: "DNS name list.", importantFields: ["dnsNames"], interpretation: ["Concatenate or decode labels if they look like data."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["run_python"],
      cost: "CHEAP",
      tags: ["dns", "pcap", "exfil"],
      run: wrap(extractDnsActivityTool),
    },
    {
      name: "carve_files",
      group: "MISC_FILE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Carve a byte range to artifacts/carved/.",
      whenToUse: ["scan_trailing_data or scan_embedded_signatures gave an offset"],
      whenNotToUse: ["Do not carve the whole file unless you have a reason"],
      prerequisites: ["Known offset"],
      schema: carveSchema,
      parameters: [
        PATH,
        { name: "offset", type: "number", required: true, description: "Start byte.", example: 128 },
        { name: "length", type: "number", required: false, description: "Byte count. Default to EOF." },
        { name: "destPath", type: "string", required: false, description: "Default artifacts/carved/at-<offset>.bin" },
        FORCE,
      ],
      examples: [{ title: "trail", situation: "Carve after IEND", args: { path: "input/a.png", offset: 80, length: 20 }, expectedSummary: "carved" }],
      output: { description: "Carved file path and size.", importantFields: ["path", "size"], interpretation: ["inspect_file the carved artifact next."] },
      failureModes: [{ code: "VALIDATION", meaning: "path+offset required.", recovery: "Use the offset from scan_trailing_data." }],
      suggestedNextTools: ["inspect_file", "extract_archive"],
      cost: "CHEAP",
      tags: ["carve", "offset", "slice"],
      run: wrap(carveFilesTool),
    },
    {
      name: "request_specialist",
      group: "SPECIALIST",
      domains: ["MISC", "CRYPTO"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Run a short structured specialist (IMAGE/PCAP/ARCHIVE/RSA/PRNG). Does not occupy a worker.",
      whenToUse: ["Need a second opinion on a file type", "RSA instance needs a cheap attack list"],
      whenNotToUse: ["Not a replacement for the real attack tools"],
      prerequisites: [],
      schema: specialistParamsSchema,
      parameters: [
        { name: "kind", type: "IMAGE|PCAP|AUDIO|ARCHIVE|RSA|PRNG|LATTICE", required: true, description: "Specialist kind." },
        { name: "path", type: "string", required: false, description: "File to inspect." },
        { name: "text", type: "string", required: false, description: "Inline text (RSA/PRNG)." },
      ],
      examples: [{ title: "rsa", situation: "Triage n/e/c", args: { kind: "RSA", text: "n=10007*10009 e=3 c=8" }, expectedSummary: "RSA" }],
      output: { description: "Conclusion, facts, recommended actions.", importantFields: ["conclusion", "recommendedActions"], interpretation: ["Follow recommendedActions via discover_tools."] },
      failureModes: [{ code: "VALIDATION", meaning: "kind required.", recovery: "Pick a kind." }],
      suggestedNextTools: ["analyze_rsa_instance", "analyze_visual"],
      cost: "CHEAP",
      tags: ["specialist", "triage"],
      run: wrap(requestSpecialistTool),
    },
  ];
}
