import {
  analyzeVisualParamsSchema,
  extractBitplaneSchema,
  extractKeyframesParamsSchema,
  imageTransformSchema,
  pathOnlySchema,
  renderSpectrogramParamsSchema,
  requestVisualReviewParamsSchema,
} from "@rio/domain";
import type { ToolDescriptor } from "./types.js";
import { analyzeVisualTool, extractKeyframesTool, renderSpectrogramTool, requestVisualReviewTool } from "../tools.js";
import { extractBitplaneTool, extractVisibleTextTool, renderTransformTool } from "../semantic-tools.js";

const PATH = { name: "path", type: "string", required: true, description: "Workspace-relative image/audio/video.", example: "input/task.png" };
const FORCE = { name: "force", type: "boolean", required: false, description: "Bypass cache / ALREADY_TESTED." };

function wrap(run: ToolDescriptor["run"]): ToolDescriptor["run"] {
  return (ctx, params, meta) => Promise.resolve(run(ctx, params, meta));
}

export function visualTools(): ToolDescriptor[] {
  return [
    {
      name: "analyze_visual",
      group: "MISC_IMAGE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Look at an image: overview, QR, channels, bitplanes. AUTO may call a vision model with a specific question.",
      whenToUse: ["File is PNG/JPEG/GIF", "Need QR / visible text / channel anomalies"],
      whenNotToUse: ["Do not ask to 'describe the image'", "Do not re-call vision on the same bytes unless transformed or force=true"],
      prerequisites: ["An image file"],
      schema: analyzeVisualParamsSchema,
      parameters: [
        PATH,
        { name: "question", type: "string", required: false, description: "Specific question. Never 'describe the image'." },
        { name: "mode", type: "AUTO|LOCAL_ONLY|VISION_MODEL", required: false, description: "Prefer LOCAL_ONLY first." },
        FORCE,
      ],
      examples: [
        { title: "local", situation: "QR / overview", args: { path: "input/task.png", mode: "LOCAL_ONLY" }, expectedSummary: "visual" },
        { title: "vision", situation: "Need to read painted text", args: { path: "input/task.png", mode: "VISION_MODEL", question: "What flag-shaped text is visible?" }, expectedSummary: "visual" },
      ],
      output: { description: "Local observations, optional QR text, optional vision JSON.", importantFields: ["qr", "summary", "observations"], interpretation: ["QR text is often the flag. Vision is evidence, not a submit."] },
      failureModes: [{ code: "VALIDATION", meaning: "path required.", recovery: "Pass path." }],
      suggestedNextTools: ["extract_bitplane", "render_transform", "request_visual_review"],
      cost: "NORMAL",
      tags: ["image", "qr", "vision", "stego"],
      run: wrap(analyzeVisualTool),
    },
    {
      name: "request_visual_review",
      group: "MISC_IMAGE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Queue a human look at an image. Does not block — continue other analysis.",
      whenToUse: ["Local and vision tools are not enough", "Need a human to read a CAPTCHA-like image"],
      whenNotToUse: ["Do not use as the first action on every PNG"],
      prerequisites: ["Specific question"],
      schema: requestVisualReviewParamsSchema,
      parameters: [
        PATH,
        { name: "question", type: "string", required: true, description: "What the human should look for." },
        { name: "reason", type: "string", required: true, description: "Why local/vision is not enough." },
      ],
      examples: [{ title: "eyes", situation: "Unreadable font", args: { path: "input/sign.png", question: "What letters are painted?", reason: "OCR backend unavailable" }, expectedSummary: "review" }],
      output: { description: "Queued. Human answer arrives later as HUMAN VISUAL OBSERVATION.", importantFields: [], interpretation: ["Keep working. Do not wait."] },
      failureModes: [{ code: "VALIDATION", meaning: "path, question, reason required.", recovery: "Fill all three." }],
      suggestedNextTools: ["analyze_visual", "extract_bitplane"],
      cost: "EXPENSIVE",
      tags: ["human", "review", "vision"],
      run: wrap(requestVisualReviewTool),
    },
    {
      name: "render_spectrogram",
      group: "MISC_AUDIO_VIDEO",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Render a spectrogram PNG from a WAV file into artifacts/visual/spectrogram.png.",
      whenToUse: ["WAV/audio attachment", "Suspected hidden image or Morse in spectrum"],
      whenNotToUse: ["Not for images or PCAPs"],
      prerequisites: ["A WAV file"],
      schema: renderSpectrogramParamsSchema,
      parameters: [
        PATH,
        { name: "mode", type: "AUTO|WIDE|DETAIL", required: false, description: "Layout." },
        { name: "maxDurationSeconds", type: "number", required: false, description: "Cap duration." },
      ],
      examples: [{ title: "wav", situation: "tone.wav", args: { path: "input/tone.wav", mode: "AUTO" }, expectedSummary: "spectrogram" }],
      output: { description: "PNG path and sample rate.", importantFields: ["path", "sampleRate"], interpretation: ["Then analyze_visual the spectrogram PNG."] },
      failureModes: [{ code: "VALIDATION", meaning: "Need a WAV.", recovery: "inspect_file first." }],
      suggestedNextTools: ["analyze_visual"],
      cost: "NORMAL",
      tags: ["audio", "wav", "spectrogram", "sstv"],
      run: wrap(renderSpectrogramTool),
    },
    {
      name: "extract_keyframes",
      group: "MISC_AUDIO_VIDEO",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Extract video/GIF/image keyframes into a contact sheet (ffmpeg for video; PNG/JPEG works without it).",
      whenToUse: ["GIF or video that may flash a flag on one frame"],
      whenNotToUse: ["Static PNG unless you just want a contact sheet"],
      prerequisites: [],
      schema: extractKeyframesParamsSchema,
      parameters: [
        PATH,
        { name: "strategy", type: "UNIFORM|SCENE_CHANGE|ALL_IF_SMALL", required: false, description: "Frame pick strategy." },
        { name: "maxFrames", type: "number", required: false, description: "1..16" },
      ],
      examples: [{ title: "still", situation: "PNG fallback", args: { path: "input/still.png", maxFrames: 4 }, expectedSummary: "keyframes" }],
      output: { description: "Contact sheet under artifacts/visual/.", importantFields: ["sheet", "frames"], interpretation: ["analyze_visual the sheet."] },
      failureModes: [{ code: "KEYFRAMES", meaning: "Need ffmpeg for this video.", recovery: "If it is a still image, pass PNG/JPEG." }],
      suggestedNextTools: ["analyze_visual"],
      cost: "NORMAL",
      tags: ["video", "gif", "frames"],
      run: wrap(extractKeyframesTool),
    },
    {
      name: "render_transform",
      group: "MISC_IMAGE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Write a transformed PNG (grayscale / invert / autocontrast / threshold / rotate).",
      whenToUse: ["Visible text is low-contrast", "Need invert/threshold before vision or QR"],
      whenNotToUse: ["Not a substitute for bitplanes"],
      prerequisites: ["An image"],
      schema: imageTransformSchema,
      parameters: [
        PATH,
        { name: "op", type: "grayscale|invert|autocontrast|threshold|rotate90|rotate180|rotate270", required: true, description: "Transform." },
        FORCE,
      ],
      examples: [{ title: "invert", situation: "Dark-on-dark text", args: { path: "input/b.png", op: "invert" }, expectedSummary: "wrote" }],
      output: { description: "New PNG path.", importantFields: ["path", "op"], interpretation: ["Re-run analyze_visual LOCAL_ONLY on the new file."] },
      failureModes: [{ code: "VALIDATION", meaning: "path+op required.", recovery: "Pick a listed op." }],
      suggestedNextTools: ["analyze_visual", "extract_bitplane"],
      cost: "CHEAP",
      tags: ["image", "transform", "invert"],
      run: wrap(renderTransformTool),
    },
    {
      name: "extract_bitplane",
      group: "MISC_IMAGE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "Extract one channel bit plane to a PNG.",
      whenToUse: ["LSB stego suspicion", "Channel anomaly in analyze_visual"],
      whenNotToUse: ["Not the first tool on a QR-only image"],
      prerequisites: ["Raster PNG/JPEG"],
      schema: extractBitplaneSchema,
      parameters: [
        PATH,
        { name: "channel", type: "0|1|2|3|R|G|B|A", required: true, description: "Channel.", example: "R" },
        { name: "bit", type: "number", required: true, description: "0 (LSB) .. 7 (MSB).", example: 0 },
        FORCE,
      ],
      examples: [{ title: "lsb", situation: "Red LSB", args: { path: "input/b.png", channel: "R", bit: 0 }, expectedSummary: "bitplane" }],
      output: { description: "Bitplane PNG path.", importantFields: ["path"], interpretation: ["analyze_visual the bitplane; look for QR or text."] },
      failureModes: [{ code: "VALIDATION", meaning: "path, channel, bit required.", recovery: "channel R bit 0 is the usual LSB start." }],
      suggestedNextTools: ["analyze_visual"],
      cost: "CHEAP",
      tags: ["lsb", "bitplane", "stego"],
      run: wrap(extractBitplaneTool),
    },
    {
      name: "extract_visible_text",
      group: "MISC_IMAGE",
      domains: ["MISC"],
      exposure: "DISCOVERABLE",
      routerExecutable: true,
      summary: "OCR visible text. Returns BACKEND_UNAVAILABLE if no OCR engine is installed.",
      whenToUse: ["Printed text in an image and no vision model"],
      whenNotToUse: ["Do not expect bundled tesseract"],
      prerequisites: ["Optional tesseract"],
      schema: pathOnlySchema,
      parameters: [PATH, FORCE],
      examples: [{ title: "ocr", situation: "No engine", args: { path: "input/b.png" }, expectedSummary: "OCR" }],
      output: { description: "Text or BACKEND_UNAVAILABLE.", importantFields: ["code", "backend"], interpretation: ["If unavailable, analyze_visual VISION_MODEL or request_visual_review."] },
      failureModes: [{ code: "BACKEND_UNAVAILABLE", meaning: "No OCR bundled.", recovery: "Use analyze_visual or request_visual_review." }],
      suggestedNextTools: ["analyze_visual", "request_visual_review"],
      cost: "NORMAL",
      tags: ["ocr", "text", "tesseract"],
      run: wrap(extractVisibleTextTool),
    },
  ];
}
